# The URL the site will be built for
base_url = "https://diogotc.com"

# The site title and description; used in feeds by default.
title = "Diogo Correia"
description = "Hey, I'm Diogo Torres Correia from Portugal. I love programming, running, taking photos and learning new things!"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The default author for pages
author = "Diogo Correia"

# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
  {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "charcoal"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => üòÑ)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `‚Ä¶`, `"quote"` into `‚Äúcurly‚Äù` etc
smart_punctuation = true

[extra]
long_title = "Diogo Torres Correia"
favicon = "/assets/images/profile.jpg"

[extra.footer]
source_code = "https://github.com/diogotcorreia/dtc-website"

[[extra.footer.socials]]
name = "mail"
label = "Email"
value = "me@diogotc.com"
link = "mailto:me@diogotc.com"
[[extra.footer.socials]]
name = "discord"
label = "Discord"
value = "diogocorreia"
link = "https://discord.com/users/218721510649626635"
[[extra.footer.socials]]
name = "matrix"
label = "Matrix"
value = "@dtc:diogotc.com"
link = "https://matrix.to/#/@dtc:diogotc.com"
[[extra.footer.socials]]
name = "mastodon"
label = "Mastodon"
value = "@dtc@masto.pt"
link = "https://masto.pt/@dtc"

[[extra.links]]
name = "Home"
path = "/"
[[extra.links]]
name = "Blog"
path = "/blog"
[[extra.links]]
name = "Impossible List"
path = "/impossiblelist"
[[extra.links]]
name = "CV"
path = "https://cv.diogotc.com"
